name: lambda-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: Use Node.js
        uses: actions/setup-node@1
        with:
          node-version: '12'
      - name: Install dependencies, Build application and Zip dist folder contents
        run: npm install && npm run build && npm run zip
      - name: deploy zip to aws lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: corona-bz-api
          zip_file: function.zip
